PKG_NAME = Attic
PKG_VERS = 0.16
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://pypi.python.org/packages/source/A/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = https://attic-backup.org/
COMMENT  = Attic is a deduplicating backup program written in Python
LICENSE  = MIT

include ../../mk/spksrc.python-wheel.mk
